def get_attributes(
	record,
	spire_genome_id,
	spire_study_id,
	spire_sample_id,
	spire_virtual_study,
	erz_assembly_id,
):

	spire_cluster = record.get("spire_v1_cluster", {}).get("name")
	checkm2_completeness = record.get("checkm2", {}).get("Completeness")
	checkm2_contamination = record.get("checkm2", {}).get("Contamination")
	n50 = record.get("checkm2", {}).get("N50")
	n_contigs = record.get("checkm2", {}).get("number")
	gunc_contamination = record.get("gunc", {}).get("contamination_portion")
	gunc_css = record.get("gunc", {}).get("clade_separation_score")
	gunc_rrs = record.get("gunc", {}).get("reference_representation_score")
	taxonomic_classification = record.get("gtdb_r214", {}).get("classification")

	attributes = {
		"sample derived from": None,
		"project name": "SPIRE v1: a Searchable Planetary-scale mIcrobiome REsource",
		"SPIRE genome id": f"spire.embl.de/spire/v1/genome/{spire_genome_id}",
		"linked to SPIRE study": f"spire.embl.de/spire/v1/study/{spire_study_id}",
		"linked to SPIRE sample": f"spire.embl.de/spire/v1/sample/{spire_sample_id}",
		"SPIRE genome cluster": f"spire.embl.de/spire/v1/cluster/{spire_cluster}",
		"linked to analysis project": f"{spire_virtual_study}",
		"derived from assembly": f"{erz_assembly_id}",
		"completeness score": f"{checkm2_completeness}",
		"contamination score": f"{checkm2_contamination}",
		"completeness software": "CheckM2 v0.1.3",
		"GUNC contaminaion score": f"{gunc_contamination}",
		"GUNC clade separation score": f"{gunc_css}",
		"GUNC reference representation score": f"{gunc_rrs}",
		"GUNC version": "GUNC v1.0.6",
		"binning software": "metaBAT2 v2.12.1",
		"binning parameters": "tetramer and coverage",
		"MAG coverage software": "bwa mem",
		"assembly software": "megahit v1.2.9",
		"assembly quality": "Many fragments with little to no review of assembly other than reporting of standard assembly statistics",
		"number of contigs": f"{n_contigs}",
		"contig N50": f"{n50}",
		"taxonomic identity marker": "multi-marker approach",
		"taxonomic classification": f"{taxonomic_classification}",
		"taxonomic classification software": "v2.3.2_r214",
		"isolation_source": "missing: third party data",
		"collection date": "missing: third party data",
		"geographic location (latitude)": "missing: third party data",
		"geographic location (longitude)": "missing: third party data",
		"geographic location (country and/or sea)": "missing: third party data",
		"broad-scale environmental context": "missing: third party data",
		"local environmental context": "missing: third party data",
		"environmental medium": "missing: third party data",
	}

	return attributes
 
 
 


d= {'_id': None,
 'bin_id': 'SAMN07632198.psa_megahit.psb_metabat2.00001',
 'bin_path': '/g/scb2/bork/data/MAGs/Angle_2017_wetland/psa_megahit/psb_metabat2/SAMN07632198.psa_megahit.psb_metabat2.00001.fa.gz',
 'checkm': {'# ambiguous bases': 0,
            '# contigs': 178,
            '# genomes': 2258,
            '# marker sets': 117,
            '# markers': 188,
            '# predicted genes': 1219,
            '# scaffolds': 178,
            '0': 131,
            '1': 57,
            '2': 0,
            '3': 0,
            '4': 0,
            '5+': 0,
            'Coding density': 86.68,
            'Completeness': 24.78,
            'Contamination': 0.0,
            'GC': 58.5,
            'GC std (scaffolds > 1kbp)': 1.58,
            'Genome size (bp)': 1304048,
            'Longest contig (bp)': 31180,
            'Longest scaffold (bp)': 31180,
            'Marker lineage': 'k__Bacteria (UID3187)',
            'Mean contig length (bp)': 7326,
            'Mean scaffold length (bp)': 7326,
            'N50 (contigs)': 9255,
            'N50 (scaffolds)': 9255,
            'Strain heterogeneity': 0.0,
            'Translation table': 11,
            'alt_drep_score': 24.78,
            'drep_score': 24.78},
 'checkm2': {'Additional_Notes': 'None',
             'Completeness': 25.32,
             'Completeness_Model_Used': 'Neural Network (Specific Model)',
             'Contamination': 0.37,
             'Gaps': 0,
             'N50': 9255,
             'N50n': 44,
             'N70': 6032,
             'N70n': 79,
             'N90': 3559,
             'N90n': 135,
             'N_count': 0,
             'Translation_Table_Used': 11,
             'alt_drep_score': 25.32,
             'longest': 31180,
             'mean_length': 7326.11,
             'number': 178,
             'shortest': 2509,
             'total_length': 1304048},
 'formatted_spire_id': 'spire_mag_01046808',
 'global_data_v1': True,
 'global_data_v1_cluster': {'assignment_method': 'fail_gunc_checkm_qc',
                            'name': None},
 'gtdb_r202': {'class': 'Acidobacteriae',
               'classification': 'd__Bacteria;p__Acidobacteriota;c__Acidobacteriae;o__Acidobacteriales;f__Gp1-AA117;g__Gp1-AA17;s__',
               'classification_method': 'taxonomic classification defined by '
                                        'topology and ANI',
               'closest_placement_af': 0.14,
               'closest_placement_ani': 77.0,
               'closest_placement_radius': 95.0,
               'closest_placement_reference': 'GCA_003140235.1',
               'closest_placement_taxonomy': 'd__Bacteria;p__Acidobacteriota;c__Acidobacteriae;o__Acidobacteriales;f__Gp1-AA117;g__Gp1-AA17;s__Gp1-AA17 '
                                             'sp003140235',
               'domain': 'Bacteria',
               'family': 'Gp1-AA117',
               'fastani_af': None,
               'fastani_ani': None,
               'fastani_reference': None,
               'fastani_reference_radius': None,
               'fastani_taxonomy': None,
               'genus': 'Gp1-AA17',
               'msa_percent': 23.25,
               'note': None,
               'order': 'Acidobacteriales',
               'other_related_references(genome_id,species_name,radius,ANI,AF)': 'GCA_003223515.1, '
                                                                                 's__Gp1-AA17 '
                                                                                 'sp003223515, '
                                                                                 '95.0, '
                                                                                 '77.46, '
                                                                                 '0.22',
               'phylum': 'Acidobacteriota',
               'pplacer_taxonomy': 'd__Bacteria;p__Acidobacteriota;c__Acidobacteriae;o__Acidobacteriales;f__Gp1-AA117;g__Gp1-AA17;s__',
               'red_value': 0.9113160627924692,
               'species': '',
               'translation_table': 11,
               'warnings': None},
 'gtdb_r207': {'class': 'Acidobacteriae',
               'classification': 'd__Bacteria;p__Acidobacteriota;c__Acidobacteriae;o__Acidobacteriales;f__Gp1-AA117;g__Gp1-AA17;s__',
               'classification_method': 'taxonomic classification defined by '
                                        'topology and ANI',
               'closest_placement_af': 0.14,
               'closest_placement_ani': 77.05,
               'closest_placement_radius': 95.0,
               'closest_placement_reference': 'GCA_003140235.1',
               'closest_placement_taxonomy': 'd__Bacteria;p__Acidobacteriota;c__Acidobacteriae;o__Acidobacteriales;f__Gp1-AA117;g__Gp1-AA17;s__Gp1-AA17 '
                                             'sp003140235',
               'domain': 'Bacteria',
               'family': 'Gp1-AA117',
               'fastani_af': None,
               'fastani_ani': None,
               'fastani_reference': None,
               'fastani_reference_radius': None,
               'fastani_taxonomy': None,
               'genus': 'Gp1-AA17',
               'msa_percent': 23.01,
               'note': 'classification based on placement in class-level tree',
               'order': 'Acidobacteriales',
               'other_related_references(genome_id,species_name,radius,ANI,AF)': 'GCA_003223515.1, '
                                                                                 's__Gp1-AA17 '
                                                                                 'sp003223515, '
                                                                                 '95.0, '
                                                                                 '77.46, '
                                                                                 '0.22',
               'phylum': 'Acidobacteriota',
               'pplacer_taxonomy': 'd__Bacteria;p__Acidobacteriota;c__Acidobacteriae;o__Acidobacteriales;f__Gp1-AA117;g__Gp1-AA17;s__',
               'red_value': 0.8862150652136096,
               'species': '',
               'translation_table': 11.0,
               'warnings': None},
 'gtdb_r214': {'class': 'Terriglobia',
               'classification': 'd__Bacteria;p__Acidobacteriota;c__Terriglobia;o__Terriglobales;f__Gp1-AA117;g__Angelobacter;s__',
               'classification_method': 'taxonomic classification defined by '
                                        'topology and ANI',
               'closest_placement_af': 0.682,
               'closest_placement_ani': 81.52,
               'closest_placement_radius': 95.0,
               'closest_placement_reference': 'GCA_020072815.1',
               'closest_placement_taxonomy': 'd__Bacteria;p__Acidobacteriota;c__Terriglobia;o__Terriglobales;f__Gp1-AA117;g__Angelobacter;s__Angelobacter '
                                             'sp020072815',
               'domain': 'Bacteria',
               'family': 'Gp1-AA117',
               'fastani_af': None,
               'fastani_ani': None,
               'fastani_reference': None,
               'fastani_reference_radius': None,
               'fastani_taxonomy': None,
               'genus': 'Angelobacter',
               'msa_percent': 23.3,
               'note': 'classification based on placement in class-level tree',
               'order': 'Terriglobales',
               'other_related_references(genome_id,species_name,radius,ANI,AF)': 'GCA_020072585.1, '
                                                                                 's__Angelobacter '
                                                                                 'sp020072585, '
                                                                                 '95.0, '
                                                                                 '77.87, '
                                                                                 '0.294; '
                                                                                 'GCA_020072645.1, '
                                                                                 's__Angelobacter '
                                                                                 'sp020072645, '
                                                                                 '95.0, '
                                                                                 '77.67, '
                                                                                 '0.268; '
                                                                                 'GCA_003223515.1, '
                                                                                 's__Angelobacter '
                                                                                 'sp003223515, '
                                                                                 '95.0, '
                                                                                 '77.46, '
                                                                                 '0.216; '
                                                                                 'GCA_003140235.1, '
                                                                                 's__Angelobacter '
                                                                                 'sp003140235, '
                                                                                 '95.0, '
                                                                                 '77.0, '
                                                                                 '0.143',
               'phylum': 'Acidobacteriota',
               'pplacer_taxonomy': 'd__Bacteria;p__Acidobacteriota;c__Terriglobia;o__Terriglobales;f__Gp1-AA117;g__Angelobacter;s__',
               'red_value': 0.94144,
               'species': '',
               'translation_table': 11.0,
               'warnings': 'Genome not assigned to closest species as it falls '
                           'outside its pre-defined ANI radius'},
 'gunc': {'clade_separation_score': 0.24,
          'contamination_portion': 0.28,
          'genes_retained_index': 0.6,
          'mean_hit_identity': 0.58,
          'n_contigs': 178,
          'n_effective_surplus_clades': 0.74,
          'n_genes_called': 1214,
          'n_genes_mapped': 1046,
          'pass_GUNC': True,
          'pass_GUNC5': True,
          'proportion_genes_retained_in_major_clades': 0.69,
          'reference_representation_score': 0.35,
          'taxonomic_level': 'order'},
 'internal': False,
 'sample_id': 'SAMN07632198',
 'spire_id': 1046808,
 'spire_v1_cluster': {'assignment_method': 'fail_gunc_checkm_qc', 'name': None},
 'study_id': 'Angle_2017_wetland',
 'taxonomy': {'class': {'ari_all': -0.08,
                        'ari_confident': 0.0,
                        'assignment_confidence': 0.0,
                        'chimerism_score_all': 0.68,
                        'chimerism_score_confident': 2.0,
                        'confident_count': 5,
                        'other_confident_count': 0,
                        'other_unconfident_count': 2,
                        'taxonomic_assignment': '204432 Acidobacteriia',
                        'total_marker_genes': 8,
                        'unconfident_count': 1,
                        'unique_marker_genes': 8},
              'family': {'ari_all': -0.08,
                         'ari_confident': -0.08,
                         'assignment_confidence': 0.0,
                         'chimerism_score_all': 0.68,
                         'chimerism_score_confident': 0.68,
                         'confident_count': 0,
                         'other_confident_count': 0,
                         'other_unconfident_count': 2,
                         'taxonomic_assignment': '204434 Acidobacteriaceae',
                         'total_marker_genes': 8,
                         'unconfident_count': 6,
                         'unique_marker_genes': 8},
              'genus': {'ari_all': -0.09,
                        'ari_confident': -0.09,
                        'assignment_confidence': 0.0,
                        'chimerism_score_all': 4.33,
                        'chimerism_score_confident': 4.33,
                        'confident_count': 0,
                        'other_confident_count': 0,
                        'other_unconfident_count': 6,
                        'taxonomic_assignment': '1775468 Silvibacterium',
                        'total_marker_genes': 8,
                        'unconfident_count': 2,
                        'unique_marker_genes': 8},
              'kingdom': {'ari_all': 0.0,
                          'ari_confident': None,
                          'assignment_confidence': 0.0,
                          'chimerism_score_all': 0.0,
                          'chimerism_score_confident': None,
                          'confident_count': 8,
                          'other_confident_count': 0,
                          'other_unconfident_count': 0,
                          'taxonomic_assignment': '2 Bacteria',
                          'total_marker_genes': 8,
                          'unconfident_count': 0,
                          'unique_marker_genes': 8},
              'motu': {'ari_all': None,
                       'ari_confident': None,
                       'assignment_confidence': 0.0,
                       'chimerism_score_all': None,
                       'chimerism_score_confident': None,
                       'confident_count': 0,
                       'other_confident_count': 0,
                       'other_unconfident_count': 3,
                       'taxonomic_assignment': 'ref_mOTU_v25_10678',
                       'total_marker_genes': 4,
                       'unconfident_count': 1,
                       'unique_marker_genes': 4},
              'order': {'ari_all': -0.08,
                        'ari_confident': -0.18,
                        'assignment_confidence': 0.0,
                        'chimerism_score_all': 0.68,
                        'chimerism_score_confident': 1.27,
                        'confident_count': 3,
                        'other_confident_count': 0,
                        'other_unconfident_count': 2,
                        'taxonomic_assignment': '204433 Acidobacteriales',
                        'total_marker_genes': 8,
                        'unconfident_count': 3,
                        'unique_marker_genes': 8},
              'phylum': {'ari_all': -0.08,
                         'ari_confident': 1.0,
                         'assignment_confidence': 0.0,
                         'chimerism_score_all': 0.68,
                         'chimerism_score_confident': 0.0,
                         'confident_count': 6,
                         'other_confident_count': 1,
                         'other_unconfident_count': 1,
                         'taxonomic_assignment': '57723 Acidobacteria',
                         'total_marker_genes': 8,
                         'unconfident_count': 0,
                         'unique_marker_genes': 8},
              'specI': {'ari_all': -0.09,
                        'ari_confident': -0.09,
                        'assignment_confidence': 0.0,
                        'chimerism_score_all': 4.33,
                        'chimerism_score_confident': 4.33,
                        'confident_count': 0,
                        'other_confident_count': 0,
                        'other_unconfident_count': 6,
                        'taxonomic_assignment': 'specI_v3_10678 658062 '
                                                'Candidatus Koribacter '
                                                'versatilis',
                        'total_marker_genes': 8,
                        'unconfident_count': 2,
                        'unique_marker_genes': 8}},
 'taxonomy_v13': {'motu': {'ari_all': None,
                           'ari_confident': None,
                           'assignment_confidence': 0,
                           'chimerism_score_all': None,
                           'chimerism_score_confident': None,
                           'confident_count': 0,
                           'other_confident_count': 0,
                           'other_unconfident_count': 0,
                           'taxonomic_assignment': 'specI_v4_16685',
                           'total_marker_genes': 4,
                           'unconfident_count': 4,
                           'unique_marker_genes': 4},
                  'specI': {'ari_all': -0.13,
                            'ari_confident': -0.13,
                            'assignment_confidence': 0,
                            'chimerism_score_all': 0.28,
                            'chimerism_score_confident': 0.28,
                            'confident_count': 0,
                            'other_confident_count': 0,
                            'other_unconfident_count': 1,
                            'taxonomic_assignment': 'specI_v4_16685',
                            'total_marker_genes': 8,
                            'unconfident_count': 7,
                            'unique_marker_genes': 8}},
 'taxonomy_v2': {'class': {'ari_all': -0.08,
                           'ari_confident': 0.0,
                           'assignment_confidence': 0.0,
                           'chimerism_score_all': 0.68,
                           'chimerism_score_confident': 2.0,
                           'confident_count': 5,
                           'other_confident_count': 0,
                           'other_unconfident_count': 2,
                           'taxonomic_assignment': '204432 Acidobacteriia',
                           'total_marker_genes': 8,
                           'unconfident_count': 1,
                           'unique_marker_genes': 8},
                 'family': {'ari_all': -0.08,
                            'ari_confident': -0.08,
                            'assignment_confidence': 0.0,
                            'chimerism_score_all': 0.68,
                            'chimerism_score_confident': 0.68,
                            'confident_count': 0,
                            'other_confident_count': 0,
                            'other_unconfident_count': 2,
                            'taxonomic_assignment': '204434 Acidobacteriaceae',
                            'total_marker_genes': 8,
                            'unconfident_count': 6,
                            'unique_marker_genes': 8},
                 'genus': {'ari_all': -0.09,
                           'ari_confident': -0.09,
                           'assignment_confidence': 0.0,
                           'chimerism_score_all': 4.33,
                           'chimerism_score_confident': 4.33,
                           'confident_count': 0,
                           'other_confident_count': 0,
                           'other_unconfident_count': 6,
                           'taxonomic_assignment': '658061 Candidatus '
                                                   'Koribacter',
                           'total_marker_genes': 8,
                           'unconfident_count': 2,
                           'unique_marker_genes': 8},
                 'kingdom': {'ari_all': 0.0,
                             'ari_confident': None,
                             'assignment_confidence': 0.0,
                             'chimerism_score_all': 0.0,
                             'chimerism_score_confident': None,
                             'confident_count': 8,
                             'other_confident_count': 0,
                             'other_unconfident_count': 0,
                             'taxonomic_assignment': '2 Bacteria',
                             'total_marker_genes': 8,
                             'unconfident_count': 0,
                             'unique_marker_genes': 8},
                 'motu': {'ari_all': None,
                          'ari_confident': None,
                          'assignment_confidence': 0.0,
                          'chimerism_score_all': None,
                          'chimerism_score_confident': None,
                          'confident_count': 0,
                          'other_confident_count': 0,
                          'other_unconfident_count': 3,
                          'taxonomic_assignment': 'ref_mOTU_v25_10678',
                          'total_marker_genes': 4,
                          'unconfident_count': 1,
                          'unique_marker_genes': 4},
                 'order': {'ari_all': -0.08,
                           'ari_confident': -0.18,
                           'assignment_confidence': 0.0,
                           'chimerism_score_all': 0.68,
                           'chimerism_score_confident': 1.27,
                           'confident_count': 3,
                           'other_confident_count': 0,
                           'other_unconfident_count': 2,
                           'taxonomic_assignment': '204433 Acidobacteriales',
                           'total_marker_genes': 8,
                           'unconfident_count': 3,
                           'unique_marker_genes': 8},
                 'phylum': {'ari_all': -0.08,
                            'ari_confident': 1.0,
                            'assignment_confidence': 0.0,
                            'chimerism_score_all': 0.68,
                            'chimerism_score_confident': 0.0,
                            'confident_count': 6,
                            'other_confident_count': 1,
                            'other_unconfident_count': 1,
                            'taxonomic_assignment': '57723 Acidobacteria',
                            'total_marker_genes': 8,
                            'unconfident_count': 0,
                            'unique_marker_genes': 8},
                 'specI': {'ari_all': -0.09,
                           'ari_confident': -0.09,
                           'assignment_confidence': 0.0,
                           'chimerism_score_all': 4.33,
                           'chimerism_score_confident': 4.33,
                           'confident_count': 0,
                           'other_confident_count': 0,
                           'other_unconfident_count': 6,
                           'taxonomic_assignment': 'specI_v3_10678 658062 '
                                                   'Candidatus Koribacter '
                                                   'versatilis',
                           'total_marker_genes': 8,
                           'unconfident_count': 2,
                           'unique_marker_genes': 8}},
 'taxonomy_v3': {'class': {'ari_all': -0.08,
                           'ari_confident': 0.0,
                           'assignment_confidence': 0.0,
                           'chimerism_score_all': 0.68,
                           'chimerism_score_confident': 2.0,
                           'confident_count': 5,
                           'other_confident_count': 0,
                           'other_unconfident_count': 2,
                           'taxonomic_assignment': '204432 Acidobacteriia',
                           'total_marker_genes': 8,
                           'unconfident_count': 1,
                           'unique_marker_genes': 8},
                 'family': {'ari_all': -0.08,
                            'ari_confident': -0.08,
                            'assignment_confidence': 0.0,
                            'chimerism_score_all': 0.68,
                            'chimerism_score_confident': 0.68,
                            'confident_count': 0,
                            'other_confident_count': 0,
                            'other_unconfident_count': 2,
                            'taxonomic_assignment': '204434 Acidobacteriaceae',
                            'total_marker_genes': 8,
                            'unconfident_count': 6,
                            'unique_marker_genes': 8},
                 'genus': {'ari_all': -0.09,
                           'ari_confident': -0.09,
                           'assignment_confidence': 0.0,
                           'chimerism_score_all': 4.33,
                           'chimerism_score_confident': 4.33,
                           'confident_count': 0,
                           'other_confident_count': 0,
                           'other_unconfident_count': 6,
                           'taxonomic_assignment': '658061 Candidatus '
                                                   'Koribacter',
                           'total_marker_genes': 8,
                           'unconfident_count': 2,
                           'unique_marker_genes': 8},
                 'kingdom': {'ari_all': 0.0,
                             'ari_confident': None,
                             'assignment_confidence': 0.0,
                             'chimerism_score_all': 0.0,
                             'chimerism_score_confident': None,
                             'confident_count': 8,
                             'other_confident_count': 0,
                             'other_unconfident_count': 0,
                             'taxonomic_assignment': '2 Bacteria',
                             'total_marker_genes': 8,
                             'unconfident_count': 0,
                             'unique_marker_genes': 8},
                 'motu': {'ari_all': None,
                          'ari_confident': None,
                          'assignment_confidence': 0.0,
                          'chimerism_score_all': None,
                          'chimerism_score_confident': None,
                          'confident_count': 0,
                          'other_confident_count': 0,
                          'other_unconfident_count': 3,
                          'taxonomic_assignment': 'ref_mOTU_v25_10678',
                          'total_marker_genes': 4,
                          'unconfident_count': 1,
                          'unique_marker_genes': 4},
                 'order': {'ari_all': -0.08,
                           'ari_confident': -0.18,
                           'assignment_confidence': 0.0,
                           'chimerism_score_all': 0.68,
                           'chimerism_score_confident': 1.27,
                           'confident_count': 3,
                           'other_confident_count': 0,
                           'other_unconfident_count': 2,
                           'taxonomic_assignment': '204433 Acidobacteriales',
                           'total_marker_genes': 8,
                           'unconfident_count': 3,
                           'unique_marker_genes': 8},
                 'phylum': {'ari_all': -0.08,
                            'ari_confident': 1.0,
                            'assignment_confidence': 0.0,
                            'chimerism_score_all': 0.68,
                            'chimerism_score_confident': 0.0,
                            'confident_count': 6,
                            'other_confident_count': 1,
                            'other_unconfident_count': 1,
                            'taxonomic_assignment': '57723 Acidobacteria',
                            'total_marker_genes': 8,
                            'unconfident_count': 0,
                            'unique_marker_genes': 8},
                 'specI': {'ari_all': -0.09,
                           'ari_confident': -0.09,
                           'assignment_confidence': 0.0,
                           'chimerism_score_all': 4.33,
                           'chimerism_score_confident': 4.33,
                           'confident_count': 0,
                           'other_confident_count': 0,
                           'other_unconfident_count': 6,
                           'taxonomic_assignment': 'specI_v3_08618 1577686 '
                                                   'Silvibacterium bohemicum',
                           'total_marker_genes': 8,
                           'unconfident_count': 2,
                           'unique_marker_genes': 8}}}